model_type: 'image'
encoder: 'retfound'
freeze_encoder: False
pretrained: True
restore_from_ckpt: False
checkpoint_path: '${BASE_PATH}/data/models/retfound/RETFound_cfp_weights.pth'
drop_path_rate: 0.2
retfound_augment: False
