defaults:
  - covariates: no_covariates
  - _self_

batch_size: 128
partition: 0
num_workers: 4
img_root: '/sc-projects/sc-proj-ukb-cvd/data/retina/preprocessed/preprocessed'

label_definition:
  all_cause_death: True
  phecodes: True
  custom: []
use_top_n_phecodes: 1000
filter_input_origins: []
use_loss_weights: False
