defaults:
  - setup: basic
  - head: mlp
  - datamodule: tte
  - model: image
  - training: default
  - _self_

trainer:
  gpus: [0]
  precision: 16
  max_epochs: 10000
  num_sanity_val_steps: -1
  detect_anomaly: False
  amp_backend: native
  accumulate_grad_batches: 1
  gradient_clip_val: 1
  #overfit_batches: 10
